#define BLOCK_NUM 128
#define BLOCK_NUM_SHORT 2688
#define BATCH_SIZE 4000 
#define NUM_READS BATCH_SIZE * 25
#define THREAD_NUM 1024
#define THREAD_NUM_MID 512
#define BLOCK_NUM_MID 252
#define THREAD_NUM_REG 1024
#define THREAD_NUM_SHORT 32
#define BLOCK_NUM_SEED 2688
#define THREAD_NUM_SEED 32
#define CHUNK_SIZE 4
#define MM_BUFFER_SIZE THREAD_NUM_SEED * (CHUNK_SIZE + 1)
#define MM_TILE_SIZE THREAD_NUM_SEED * CHUNK_SIZE
#define READ_BATCH_SIZE_SEED BLOCK_NUM
#define MEM_FACTOR 5
#define MAX_SEQ_LEN 10000
#define MAX_GAP_NUM 100

#define DBLOCK_SIZE 128
#define DBLOCK_SIZE_D 64

#define MAX_OCC 748

#define BW_EXTEND 1
#define BW_GAPFILL 30001

#define MAX_ITER_CHAIN 5000
#define MID_RANGE_CUT 512
#define LONG_RANGE_CUT 512*10
#define READ_SEG 512
#define MM_QSPAN 15

//#define TB_BUF_SIZE 8192
#define TB_BUF_SIZE 2048 
#define TB_BUF_SIZE_EXT TB_BUF_SIZE/(DBLOCK_SIZE/16)

